MODULES=leap_year
OBJECTS=$(MODULES:=.cmo)
MLS=$(MODULES:=.ml)
MLIS=$(MODULES:=.mli)
TEST=leap_year_test.byte
OCAMLBUILD=ocamlbuild -use-ocalmfind -plugin-tag 'package(bisect_ppx_ocamlbuild)'
PKGS=ounit2

default: 

# not finished